/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package E_Zughin;

import view.CenterOnDeafultScreen;

public class App {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) {
        System.out.println(new App().getGreeting());
        new CenterOnDeafultScreen(2);
    }
}
